// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axnxpddrlbvniugnyxlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4bnhwZGRybGJ2bml1Z255eGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTY1MDQsImV4cCI6MjA2MDUzMjUwNH0.SHkr4yeQWnPPOqsfCu-yWr5q74WQaGxVomm9mMExXGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);